Add two randomly generated Numpy matrices

In [2]:
import numpy as np
A1 = np.random.rand(5,4)
print(A1)
print(A1.shape)

[[0.00399035 0.14761237 0.06132661 0.20663699]
 [0.86337128 0.25636906 0.16564672 0.02936469]
 [0.13001987 0.74226342 0.96703645 0.45659003]
 [0.80680545 0.7690803  0.77483751 0.70554891]
 [0.03085907 0.76526702 0.90675015 0.42601527]]
(5, 4)


In [4]:
type(A1)

numpy.ndarray

In [6]:
A2 = np.random.rand(5,4)
print(A2)
print(A2.shape)

[[0.02949991 0.38600245 0.86743945 0.53663333]
 [0.71436195 0.48350524 0.25727573 0.53395101]
 [0.93624096 0.68712393 0.37108806 0.92277113]
 [0.78420213 0.99968156 0.40357736 0.8205077 ]
 [0.93178339 0.26053877 0.91864313 0.59853141]]
(5, 4)


In [7]:
print(A2[2,3])

0.9227711258598482


In [8]:
B = A1 + A2
print(B)

[[0.03349026 0.53361483 0.92876606 0.74327032]
 [1.57773324 0.7398743  0.42292245 0.5633157 ]
 [1.06626082 1.42938735 1.33812451 1.37936116]
 [1.59100758 1.76876186 1.17841487 1.5260566 ]
 [0.96264246 1.02580579 1.82539327 1.02454668]]


In [12]:
(r,c) = A1.shape
print(r,c)

5 4


In [11]:
for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
print(B)

[[0.03349026 0.53361483 0.92876606 0.74327032]
 [1.57773324 0.7398743  0.42292245 0.5633157 ]
 [1.06626082 1.42938735 1.33812451 1.37936116]
 [1.59100758 1.76876186 1.17841487 1.5260566 ]
 [0.96264246 1.02580579 1.82539327 1.02454668]]


In [15]:
B = np.zeros((5,4))
print(B)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
A3 = np.random.rand(2,3,4)
A4 = np.random.rand(2,3,4)

In [17]:
(a,b,c) = A3.shape

In [20]:
for i in range(a):
    for j in range(b):
        for k in range(c):
            B[i,j,k] = A1[i,j,k] + A2[i,j,k]
print(B)

IndexError: too many indices for array

Find if a 2D point is inside or outside a circle 

In [25]:
print("Cx,Cy,r:")
(Cx, Cy, r) = input().split()
print(Cx, Cy, r)

Cx,Cy,r:
1 5 6
1 5 6


In [26]:
print("Px,Py:")
(Px, Py) = input().split()

Px,Py:
2 2


In [27]:
import math


In [28]:
d = math.sqrt((Cx-Px)^2 + (Cy-Py)^2)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Numpy manipulations

In [29]:
A = np.random.rand(5,4)
print(A)

[[0.39919972 0.32948716 0.80591433 0.59506567]
 [0.07010039 0.65488418 0.1199566  0.380828  ]
 [0.13454713 0.60993139 0.27697653 0.57144485]
 [0.94733798 0.6663188  0.45261189 0.70412084]
 [0.73941509 0.66893697 0.21430154 0.53435434]]


In [30]:
B = np.reshape(A,20,'C')
print(B)

[0.39919972 0.32948716 0.80591433 0.59506567 0.07010039 0.65488418
 0.1199566  0.380828   0.13454713 0.60993139 0.27697653 0.57144485
 0.94733798 0.6663188  0.45261189 0.70412084 0.73941509 0.66893697
 0.21430154 0.53435434]
